### ISSUE TITLE
How To append system.categories to a device not overwriting existing categories.

### ISSUE THREAD

**Issue by DII-dsward** [ansible-collections/logicmonitor#1]
I need to append a category to the existing list of properties in system.categories. Can action: add and action: update be used to overwrite system.categories or append as needed? Or should we submit a feature request to have an append: true capability?

- name: Updating LM Device
      block:
        - name: Update devices facts in LM
          delegate_to: localhost
          lm_device:
            action: update
            company: "{{ lm_company }}"
            access_id: "{{ lm_access_id }}"
            access_key: "{{ lm_access_key }}"
            display_name: "{{ inventory_hostname_short }}"
            collector_id: "{{ lm_collector_id }}"
            hostname: "{{ inventory_hostname }}"
            properties: {
              system.categories: categoryToAppend
            }

**Comment by lmcalvar** [comment]
Sorry about the late response, but we didn't have issues notifications properly enabled (now fixed). Actions add & update should properly append a category to any parent groups categories in the following way:

- Parent group A has category "x"
- Device B being updated has category "y" and parent category "x" -> `["y", "x"]`

Update Device Playbook has the following field
```
properties: {
system.categories: "z"
}
```
Result:

- Group A still has category "x"
- Device B has category "y" updated to "z" but still has parent category "x" -> `["z", "x"]`

Similarly, if device C under group A were being added with category "q", it would have two categories -> `["q", "x"]`

**Comment by lmcalvar** [comment]
@DII-dsward Sorry about the late response, but we didn't have issues notifications properly enabled (now fixed). Actions add & update should properly append a category to any parent groups categories in the following way:

- Parent group A has category "x"
- Device B being updated has category "y" and parent category "x" -> `["y", "x"]`

Update Device Playbook has the following field
```
properties: {
system.categories: "z"
}
```
Result:

- Group A still has category "x"
- Device B has category "y" updated to "z" but still has parent category "x" -> `["z", "x"]`

Similarly, if device C under group A were being added with category "q", it would have two categories -> `["q", "x"]`
